export const REDUX_ACTIONS = {
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  OPEN_SNACKBAR: 'OPEN_SNACKBAR',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR',
  SIGN_IN_USER: 'SIGN_IN_USER',
  LOADING_STATES: 'LOADING_STATES',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
  GET_USER_SUGGESTIONS: 'GET_USER_SUGGESTIONS',
  DESTROY_SESSION: 'DESTROY_SESSION',
};
